### ISSUE TITLE
Decide on javascript documentation standard

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/LabControl#529]

**Comment by charles-cowart** [comment]
At the last Code Review, it was suggested Marcus write up a 'best-practices' for javascript and GUI-related coding for the lab. @AmandaBirmingham and/or @charles-cowart can touch base with him.

**Comment by charles-cowart** [comment]
@fedarko would you or @qiyunzhu like to comment on a documentation standard for the javascript? If you don't have ideas, I will table this until after full release.

**Comment by charles-cowart** [comment]
@fedarko @qiyunzhu Please comment on whether there is an existing standard you'd like to use, or whether you'd prefer to table this for after the launch. It would be good to make a decision before any more code is written or changed.

**Comment by qiyunzhu** [comment]
My opinion is to NOT set up any JavaScript coding style guideline. This is because front end programming is a fast evolving field. There are many coding styles. The mainstream ones are Google, Airbnb and GitHub. In large projects, people would specify one special coding style definition per project, using Node.js, and have Eslint checking the code. This definition may not be any of the three, but is tailored to address very specific requirements, such as whether ES6 is enabled / mandatory, whether IE10 needs to be supported, etc. Doing these is an overkill for us. Based on these observations, I believe that forcing one particular criterion will only make things more confusing and leverage the bar for people to contribute. @charles-cowart

**Comment by fedarko** [comment]
@charles-cowart: Apologies for the severely delayed response.

For just basic style I'm a fan of the ["prettier" auto-formatter](https://github.com/prettier/prettier) (fairly easy to set up—if you've used [black](https://black.readthedocs.io/en/stable/) for python code then this is basically that but for JS/HTML/CSS), but I don't have much familiarity with things like docstring standards or formal guidelines like @qiyunzhu mentioned.

Agreed with Qiyun that setting this kind of infrastructure up right now might be overkill, though. Auto-formatting solutions like prettier could be dropped into the project in the future without investing a lot more effort than would be required to do so now, and taking the time to ensure adherence to some sort of style guide throughout the codebase right now would probably be a pain (and IMO not the best use of developer time).

**Comment by charles-cowart** [comment]
@fedarko Prettier does look like it'd be worthwhile to use - what do you think, @qiyunzhu?

**Comment by qiyunzhu** [comment]
I used Beautify. Haven't tried Prettier yet.

**Comment by charles-cowart** [comment]
It sounds like  if we can try to make the code a little easier to look at with either prettier or beautify, then that's enough for now. Let's make it a point to run any js code we work on through one of the two, and if there's a benefit, check that in.
